apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-assistant-client
  labels:
    app: ai-assistant-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-assistant-client
  template:
    metadata:
      labels:
        app: ai-assistant-client
    spec:
      containers:
        - name: web
          image: iamvegetaaj/ai-assistant-client:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 256Mi

